# Generated by Django 4.1.7 on 2023-04-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=122)),
                ('p_name', models.CharField(max_length=122)),
                ('p_image', models.ImageField(upload_to='products/')),
                ('p_price', models.CharField(max_length=122)),
            ],
        ),
    ]
